force-app/main/default/objects/Stocked_Product__c/Stocked_Product__c.object-meta.xml
<CustomObject>
    <label>Stocked Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocked_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stocked_Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand1</fullName>
            </value>
            <value>
                <fullName>Brand2</fullName>
            </value>
            <value>
                <fullName>Brand3</fullName>
            </value>
            <value>
                <fullName>Brand4</fullName>
            </value>
            <value>
                <fullName>Brand5</fullName>
            </value>
            <value>
                <fullName>Brand6</fullName>
            </value>
            <value>
                <fullName>Brand7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stocked_Product__c/fields/Product_Ex_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Ex_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Ex Id</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Store Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Is_External_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Stocked_Product__c</referenceTo>
    <relationshipLabel>Store Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Products</relationshipLabel>
    <relationshipName>Store_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    private static final Integer MAX_NUM_BRANDS = 7;
    private static final Integer MAX_NUM_CATEGORIES = 4;
    private static final Integer MAX_QUANTITY = 100;
    
    public static void createStores(Integer numOfStores)
    {
        List<Account> stores = new List<Account>();
        for(Integer i=1; i <= numOfStores; i++)
        {
            stores.add(new Account(Name='Store' + i));
        }
        System.Database.insert(stores);
    }
    
    public static void createExternalStockedProducts(Integer numOfProds)
    {
        List<Stocked_Product__c> prods = new List<Stocked_Product__c>();
        for(Integer i=1; i <= numOfProds; i++)
        {
            prods.add(new Stocked_Product__c(Name = 'Product' + i,
                                             Category__c = 'Category' + Utils.getRandomInteger(1, MAX_NUM_CATEGORIES),
                                             Brand__c = 'Brand' + Utils.getrandomInteger(1, MAX_NUM_BRANDS)
                                            ));
        }
        
        System.Database.insert(prods);
    }
    
    public static void createExternalStoreProducts(Integer numOfProds)
    {
        List<Store_Product__c> storeProducts = new List<Store_Product__c>();
        List<Account> stores = [SELECT Id FROM Account];
        List<Stocked_Product__c> stockedProds = [SELECT Id FROM Stocked_Product__c 
                                                 WHERE Product_Ex_Id__c = null];
        
        for(Integer i=0; i < numOfProds; i++)
        {
            storeProducts.add(new Store_Product__c(Name = 'Stock' + i,
                                                   Quantity__c = Utils.getRandomInteger(MAX_QUANTITY),
                                                   Store__c = getRandomStore(stores).id,
                                                   Product__c = getRandomProduct(stockedProds).id,
                                                   Is_External_Product__c = True));
        }
        
        System.Database.insert(storeProducts);
    }
    
    public static void createInternalStore()
    {
        Account internalStore = new Account(Name = 'INTERNAL_STORE');
        insert internalStore;
    }
    
    public static void createInternalStockedProducts()
    {
        List<Stocked_Product__c> externalProds = [SELECT Name, Category__c, Brand__c 
                                                  FROM Stocked_Product__c 
                                                  WHERE Product_Ex_Id__c = null];
        List<Stocked_Product__c> internalProds = new List<Stocked_Product__c>();
        
        for(Stocked_Product__c eachExProd : externalProds)
        {
            internalProds.add(new Stocked_Product__c(Name = eachExProd.Name,
                                                     Category__c = eachExProd.Category__c,
                                                     Brand__c = eachExProd.Brand__c,
                                                     Product_Ex_Id__c = eachExProd.Id
                                                    ));
        }
        
        System.Database.insert(internalProds);
    }
    
    public static void createInternalStoreProducts()
    {
        List<Store_Product__c> storeProducts = new List<Store_Product__c>();
        Account internalStore = [SELECT Id FROM Account WHERE Name='INTERNAL_STORE' LIMIT 1];
        List<Stocked_Product__c> internalStockedProds = [SELECT Id FROM Stocked_Product__c
                                                         WHERE Product_Ex_Id__c != null];
        
        for(Integer i=0; i < internalStockedProds.size(); i++)
        {
            storeProducts.add(new Store_Product__c(Name = 'Stock' + i,
                                                   Quantity__c = Utils.getRandomInteger(MAX_QUANTITY),
                                                   Store__c = internalStore.id,
                                                   Product__c = internalStockedProds[i].id,
                                                   Is_External_Product__c = False));
        }
        
        System.debug(storeProducts.size());
        
        System.Database.insert(storeProducts);
    } 
    
    @testVisible
    private static Account getRandomStore(List<Account> stores)
    {
        return stores.size() == 1 ? stores[0] : stores[Utils.getRandomInteger(stores.size() - 1)];
    }
    
    @testVisible
    private static Stocked_Product__c getRandomProduct(List<Stocked_Product__c> prods)
    {
        return prods.size() == 1 ? prods[0] : prods[Utils.getRandomInteger(prods.size() - 1)];
    }
    
}