force-app/main/default/objects/Stocked_Product__c/Stocked_Product__c.object-meta.xml
<CustomObject>
    <label>Stocked Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocked_Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stocked_Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand1</fullName>
            </value>
            <value>
                <fullName>Brand2</fullName>
            </value>
            <value>
                <fullName>Brand3</fullName>
            </value>
            <value>
                <fullName>Brand4</fullName>
            </value>
            <value>
                <fullName>Brand5</fullName>
            </value>
            <value>
                <fullName>Brand6</fullName>
            </value>
            <value>
                <fullName>Brand7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stocked_Product__c/fields/Product_Ex_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Ex_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Ex Id</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Store Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Is_External_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_External_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is External Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Stocked_Product__c</referenceTo>
    <relationshipLabel>Store Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Products</relationshipLabel>
    <relationshipName>Store_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory_TEST.cls
@isTest
public with sharing class TestDataFactory_TEST {

    @isTest
    static void doesCreateStoresMakeStores()
    {
        Integer storesToGenerate = 100;
        Integer startingStores = [SELECT Count() FROM Account];
        
        Test.startTest();
        TestDataFactory.createStores(storesToGenerate);
        Test.stopTest();
        
        Integer endingStores = [SELECT Count() FROM Account];
        System.assertEquals(startingStores + storesToGenerate, endingStores);
    }

    @isTest
    static void doesCreateExternalStockedProductsMakeExternalProducts()
    {
        Integer productsToGenerate = 1000;
        Integer startingProducts = [SELECT Count() FROM Account];
        
        Test.startTest();
        TestDataFactory.createStores(productsToGenerate);
        Test.stopTest();
        
        Integer endingProducts = [SELECT Count() FROM Account];
        System.assertEquals(startingProducts + productsToGenerate, endingProducts);
    }

    @isTest
    static void doesCreateExternalStoreProductsMakeExternalProducts()
    {
        Integer numOfStores = 10;
        Integer numOfStockedProds = 100;
        Integer numOfStoreProds = 400;

        // Prefer not to call other functions here to generate data,
        // but will do so to speed things along. We will call it good
        // as long as the called functions are passing their tests :)
        TestDataFactory.createStores(numOfStores);
        TestDataFactory.createExternalStockedProducts(numOfStockedProds);
        
        Test.startTest();
        TestDataFactory.createExternalStoreProducts(numOfStoreProds);
        Test.stopTest();

        // Ensure quantity
        List<Store_Product__c> prods = [SELECT Id, Store__c, Product__c FROM Store_Product__c];
        System.assertEquals(numOfStoreProds, prods.size());

        // Grab generated store/stocked product Ids
        Map<Id, Account> storesById = new Map<Id, Account>([SELECT Id FROM Account]);
        Map<Id, Stocked_Product__c> prodsById = new Map<Id, Stocked_Product__c>([SELECT Id FROM Stocked_Product__c]);

        // Sample random generated products and assert valid relationship ids
        Set<Integer> indicesToTest = Utils.getRandomIndices(prods.size(), 10);
        for(Integer i : indicesToTest)
        {
            System.assert(storesById.keySet().contains(prods[i].Store__c));  
            System.assert(prodsById.keySet().contains(prods[i].Product__c)); 
        }
    }

    @isTest
    static void doesCreateInternalStoreMakeStore()
    {
        TestDataFactory.createInternalStore();
        List<Account> store = [SELECT Id FROM Account
        WHERE Name = 'INTERNAL_STORE'];
        System.assertEquals(1, store.size());
    }

    @isTest
    static void doesCreateInternalStockedProductsMakeProducts()
    {
        Integer numOfStores = 10;
        Integer numOfStockedProds = 100;

        // Prefer not to call other functions here to generate data,
        // but will do so to speed things along. We will call it good
        // as long as the called functions are passing their tests :)
        TestDataFactory.createStores(numOfStores);
        TestDataFactory.createInternalStore();
        TestDataFactory.createExternalStockedProducts(numOfStockedProds);

        Test.startTest();
        TestDataFactory.createInternalStockedProducts();
        Test.stopTest();

        List<Stocked_Product__c> internalProds = [SELECT Id, Product_Ex_Id__c FROM Stocked_Product__c
        WHERE Product_Ex_Id__c != null];
        
        // Ensure quantity
        System.assertEquals(numOfStockedProds, internalProds.size());

        // Grab external products Ids
        Map<Id, Stocked_Product__c> extProdsById = new Map<Id, Stocked_Product__c>([SELECT Id FROM Stocked_Product__c
        WHERE Product_Ex_Id__c = null]);
        Set<Id> extProdIds = extProdsById.keyset();

        // Check if every internal product matches an external product
        for(Stocked_Product__c eachIntProd : internalProds)
        {
            System.assert(extProdIds.contains(eachIntProd.Product_Ex_Id__c));
            extProdIds.remove(eachIntProd.Product_Ex_Id__c);
        }
        System.assertEquals(0, extProdIds.size());
    }

    @isTest
    static void doesCreateInternalStoreProductsMakeInternalProducts()
    {
        Integer numOfStores = 10;
        Integer numOfStockedProds = 100;

        // Prefer not to call other functions here to generate data,
        // but will do so to speed things along. We will call it good
        // as long as the called functions are passing their tests :)
        TestDataFactory.createStores(numOfStores);
        TestDataFactory.createInternalStore();
        TestDataFactory.createExternalStockedProducts(numOfStockedProds);
        TestDataFactory.createInternalStockedProducts();
        
        Test.startTest();
        TestDataFactory.createInternalStoreProducts();
        Test.stopTest();

        // Get internal store
        //Account internalStore = [SELECT Id FROM Account LIMIT 1];
        List<Store_Product__c> internalProds = [SELECT Id, Product__c FROM Store_Product__c
        WHERE Store__r.Name='INTERNAL_STORE' AND Is_External_Product__c = False];
        
        // Ensure quantity
        System.assertEquals(numOfStockedProds, internalProds.size());

        // Grab internal stocked products Ids
        Map<Id, Stocked_Product__c> intStockedProdsById = new Map<Id, Stocked_Product__c>([SELECT Id FROM Stocked_Product__c
        WHERE Product_Ex_Id__c != null]);
        Set<Id> intStockedProdIds = intStockedProdsById.keyset();

        // Check if every internal product matches an external product
        for(Store_Product__c eachIntProd : internalProds)
        {
            System.assert(intStockedProdIds.contains(eachIntProd.Product__c));
            intStockedProdIds.remove(eachIntProd.Product__c);
        }
        System.assertEquals(0, intStockedProdIds.size());
    }

    @isTest
    static void doesGetRandomStoreReturnRandomStore()
    {
        // throwaway for coverage
        List<Account> accs = new List<Account>();
        accs.add(new Account(Name='blablabla'));
        Account x = TestDataFactory.getRandomStore(accs);
    }

    @isTest
    static void doesGetRandomProductReturnRandomProduct()
    {
        // throwaway for coverage
        List<Stocked_Product__c> prods = new List<Stocked_Product__c>();
        prods.add(new Stocked_Product__c(Name='blablabla', Brand__c='Brand1',
         Category__c='Cat1', Product_Ex_Id__c = null));
        Stocked_Product__c x = TestDataFactory.getRandomProduct(prods);
    }
}